# Generated by Django 6.0.7 on 2026-07-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Pequeño'), ('MEDIUM', 'Mediano'), ('LARGE', 'Grande')], default='MEDIUM', max_length=10),
        ),
    ]
