# Generated by Django 6.0.7 on 2026-07-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_alter_dog_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
