# Generated by Django 6.0.7 on 2026-07-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_photograph_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='estimated_age_unit',
            field=models.CharField(choices=[('MONTHS', 'Meses'), ('YEARS', 'Años')], default='YEARS', max_length=10),
        ),
    ]
