# Generated by Django 6.0.7 on 2026-07-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0004_dog_estimated_age_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='adoption_status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible'), ('ADOPTED', 'Adoptado')], default='AVAILABLE', max_length=20),
        ),
    ]
