# Generated by Django 6.0.7 on 2026-07-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0005_alter_dog_adoption_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adoptionapplication',
            constraint=models.UniqueConstraint(fields=('user', 'dog'), name='unique_user_dog_application'),
        ),
    ]
